### PR TITLE
Changes for vpduserv

### PR DESCRIPTION
**Pull request by xiar**
1. When set password with 'password', the pdu index should be 1, 2, ...
2. Change "to_pdu" to "to_oid_pdu" to make it  more meaningful
3. Put the network function into NetworkUtils to make it better
organized.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T36699_idic_IPMILanPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36699_idic_IPMILanPrint 
TestName: T33284_idic_SOLConnect 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33284_idic_SOLConnect 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T73327_idic_SelInfoEntriesCountCheck 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T73327_idic_SelInfoEntriesCountCheck 
TestName: T36706_idic_vBMCDataEmulation 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36706_idic_vBMCDataEmulation 
TestName: T36704_idic_IPMISdrList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36704_idic_IPMISdrList 
TestName: T36703_idic_IPMISelList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36703_idic_IPMISelList 
TestName: T36702_idic_IPMIUserCommand 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36702_idic_IPMIUserCommand 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T43943_idic_IPMISIMHelpAccessible 
TestName: T36700_idic_IPMIFruPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36700_idic_IPMIFruPrint 
TestName: T33227_idic_vBMCAddSelThroughSensor 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33227_idic_vBMCAddSelThroughSensor 
TestName: T33226_idic_vBMCAddSelThroughCommand 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33226_idic_vBMCAddSelThroughCommand 
TestName: T36701_idic_IPMISensorList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36701_idic_IPMISensorList 
TestName: T46140_idic_IPMISIMSelAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T46140_idic_IPMISIMSelAccessible 
TestName: T46141_idic_IPMISIMHistoryAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T46141_idic_IPMISIMHistoryAccessible 
TestName: T33252_idic_IPMILocalSdrList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33252_idic_IPMILocalSdrList 
TestName: T36698_idic_IPMILocalUserList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T36698_idic_IPMILocalUserList 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33250_idic_KCSFruSensorList 
TestName: T33251_idic_IPMILocalSelList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33251_idic_IPMILocalSelList 
TestName: T33249_idic_IPMILocalLanPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33249_idic_IPMILocalLanPrint 
TestName: T33248_idic_KCSFruPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T33248_idic_KCSFruPrint 
TestName: T46194_idic_QEMUBootAutomatically 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465208052.25 BMC IP is not valid: None,  Failed to config runtime stack environment for T46194_idic_QEMUBootAutomatically 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
TestName: T33251_idic_KCSSelList 
ErrorMessage: Failed to issue local IPMI command ipmitool sel list, return: {'exitcode': -1, 'stdout': ''} 
TestName: T33249_idic_KCSLanPrint 
ErrorMessage: Failed to issue local IPMI command ipmitool lan, return: {'exitcode': -1, 'stdout': ''} 
TestName: T33248_idic_KCSFruPrint 
ErrorMessage: Fail to boot node to disk: Fail to set VM vbmc_quanta_d51_pr.ova_1465267231.36 to boot from disk 
TestName: T46194_idic_QEMUBootAutomatically 
ErrorMessage: Failed to automatically boot process of QEMU. 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Unexpected exception happened in config(),                         trace back:  Traceback (most recent call last):   File "/home/ci/workspace/smoke_test/test/case/CBaseCase.py", line 411, in run     self.deconfig()   File "/home/ci/workspace/smoke_test/test/case/infrasim/virtual_pdu/T36713_idic_ControlNodePower.py", line 86, in deconfig     format(obj_node.get_name())) IndexError: tuple index out of range 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Fail to boot node to disk: Fail to set VM vbmc_dell_c6320_pr.ova_1465282869.6 to boot from disk 
TestName: T33251_idic_KCSSelList 
ErrorMessage: Fail to boot node to disk: Fail to set VM vbmc_dell_c6320_pr.ova_1465282869.6 to boot from disk 
TestName: T33249_idic_KCSLanPrint 
ErrorMessage: Fail to boot node to disk: Fail to set VM vbmc_dell_c6320_pr.ova_1465282853.06 to boot from disk 
TestName: T33248_idic_KCSFruPrint 
ErrorMessage: Node vbmc_dell_c6320_pr.ova_1465282853.06 host get "frp print" result on KCS is unexpected, rsp {     "exitcode": -1,      "stdout": "" },  Node vbmc_dell_c6320_pr.ova_1465282853.06 host get "frp print 0" result on KCS is unexpected {     "exitcode": -1,      "stdout": "" } 
TestName: T73325_idic_StressPowerControl 
ErrorMessage: [2/10] Node vbmc_dell_c6320_pr.ova_1465282869.6 fail to response IOL command 1 minutes after AC on, ret: -1, completion code: , rsp: [],  Stress power control fail at 2/10, time consumption: 677.665386915 s 
TestName: T33258_idic_vPDUBasicInfo 
ErrorMessage: Node vbmc_dell_c6320_pr.ova_1465282869.6 is not ready after 1 minutes power on retry,  Failed to config runtime stack environment for T33258_idic_vPDUBasicInfo 
TestName: T37571_idic_SensorThresholdSetting 
ErrorMessage: Unexpected exception happened during case running, trace back:  Traceback (most recent call last):   File "/home/ci/workspace/smoke_test/test/case/CBaseCase.py", line 337, in run     self.test()   File "/home/ci/workspace/smoke_test/test/case/probation/T37571_idic_SensorThresholdSetting.py", line 35, in test     sensor = self.data[fru['Product Name']] KeyError: 'PowerEdge C6320' 
TestName: T78170_idic_IPMISIMHistory30Commands 
ErrorMessage: When history has more than 30 entries, the last 3 entries are expected to be "sel", "sensor", "help".See log for actual entries.Rack is vRack1, Node is vbmc_dell_c6320_pr.ova_1465282869.6, BMC IP is: 192.168.131.195,  When history has more than 30 entries, the last 3 entries are expected to be "sel", "sensor", "help".See log for actual entries.Rack is vRack1, Node is vbmc_dell_c6320_pr.ova_1465282853.06, BMC IP is: 192.168.131.194 
TestName: T46141_idic_IPMISIMHistoryAccessible 
ErrorMessage: When history has less than 30 entries, the last 3 entries are expected to be "help", "help sensor", "sensor".See log for actual entries.Rack is vRack1, Node is vbmc_dell_c6320_pr.ova_1465282869.6, BMC IP is: 192.168.131.195,  When history has less than 30 entries, the last 3 entries are expected to be "help", "help sensor", "sensor".See log for actual entries.Rack is vRack1, Node is vbmc_dell_c6320_pr.ova_1465282853.06, BMC IP is: 192.168.131.194 
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Unexpected exception happened in config(),                         trace back:  Traceback (most recent call last):   File "/home/ci/workspace/smoke_test/test/case/CBaseCase.py", line 411, in run     self.deconfig()   File "/home/ci/workspace/smoke_test/test/case/infrasim/virtual_pdu/T36713_idic_ControlNodePower.py", line 86, in deconfig     format(obj_node.get_name())) IndexError: tuple index out of range 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Node vbmc_dell_r630_pr.ova_1465294273.6 in unexpected status after T36713, last ipmitool retry ret: -1 
```

**Comment by turtle-fly** [comment]
@xiar one node's ipmi_sim (both server and client) fail to start.
Environment is left on stack 192.168.190.7.

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33284_idic_SOLConnect 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T33284_idic_SOLConnect 
TestName: T36699_idic_IPMILanPrint 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36699_idic_IPMILanPrint 
TestName: T36700_idic_IPMIFruPrint 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36700_idic_IPMIFruPrint 
TestName: T36701_idic_IPMISensorList 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36701_idic_IPMISensorList 
TestName: T36702_idic_IPMIUserCommand 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36702_idic_IPMIUserCommand 
TestName: T36703_idic_IPMISelList 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36703_idic_IPMISelList 
TestName: T36704_idic_IPMISdrList 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36704_idic_IPMISdrList 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T43943_idic_IPMISIMHelpAccessible 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T73327_idic_SelInfoEntriesCountCheck 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T73327_idic_SelInfoEntriesCountCheck 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T33250_idic_KCSFruSensorList 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T33250_idic_KCSFruSensorList 
TestName: T33258_idic_vPDUBasicInfo 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T33258_idic_vPDUBasicInfo 
TestName: T33270_idic_vPDUSetPassword 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T33270_idic_vPDUSetPassword 
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1465335869.01 BMC IP is not valid: None,  Failed to config runtime stack environment for T36713_idic_ControlNodePower 
```

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
```

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33284_idic_SOLConnect 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T33284_idic_SOLConnect 
TestName: T36699_idic_IPMILanPrint 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36699_idic_IPMILanPrint 
TestName: T36700_idic_IPMIFruPrint 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36700_idic_IPMIFruPrint 
TestName: T36701_idic_IPMISensorList 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36701_idic_IPMISensorList 
TestName: T36702_idic_IPMIUserCommand 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36702_idic_IPMIUserCommand 
TestName: T36703_idic_IPMISelList 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36703_idic_IPMISelList 
TestName: T36704_idic_IPMISdrList 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T36704_idic_IPMISdrList 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T43943_idic_IPMISIMHelpAccessible 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T73327_idic_SelInfoEntriesCountCheck 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T73327_idic_SelInfoEntriesCountCheck 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Node vbmc_s2600wtt_pr.ova_1465811047.55 BMC IP is not valid: None,  Failed to config runtime stack environment for T33250_idic_KCSSensorList 
```

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33284_idic_SOLConnect 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T33284_idic_SOLConnect 
TestName: T36699_idic_IPMILanPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36699_idic_IPMILanPrint 
TestName: T36700_idic_IPMIFruPrint 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36700_idic_IPMIFruPrint 
TestName: T36701_idic_IPMISensorList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36701_idic_IPMISensorList 
TestName: T36702_idic_IPMIUserCommand 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36702_idic_IPMIUserCommand 
TestName: T36703_idic_IPMISelList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36703_idic_IPMISelList 
TestName: T36704_idic_IPMISdrList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T36704_idic_IPMISdrList 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T43943_idic_IPMISIMHelpAccessible 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T73327_idic_SelInfoEntriesCountCheck 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T73327_idic_SelInfoEntriesCountCheck 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T46139_idic_IPMISIMSensorAccessible 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Node vbmc_dell_r730xd_pr.ova_1465828462.5 BMC IP is not valid: None,  Failed to config runtime stack environment for T33250_idic_KCSSensorList 
```

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
```

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
@xiar @turtle-fly smoke test passes for this PR!

**Comment by turtle-fly** [comment]
@PaynePei now our daily CI can have a scale larger then 24 nodes :-)

**Pull request merged**
