### PR TITLE
Change the way of vpdu service start

### PR DESCRIPTION
**Pull request by xiar**
1. Merge infrasim-pdusimd to infrasim-pduserv
2. Remove infrasim-pdsimd upstart
3. Update README.me

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Node vbmc_dell_r630_pr.ova_1467600872.31 in unexpected status after T36713, last ipmitool retry ret: -1 
```

**Comment by xiar** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* PDU_pull_request_trigger ******* 
TestName: T33258_idic_vPDUBasicInfo 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1467901960.3 BMC IP is not valid: None,  Failed to config runtime stack environment for T33258_idic_vPDUBasicInfo 
TestName: T33270_idic_vPDUSetPassword 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1467901960.3 BMC IP is not valid: None,  Failed to config runtime stack environment for T33270_idic_vPDUSetPassword 
TestName: T36713_idic_ControlNodePower 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1467901960.3 BMC IP is not valid: None,  Failed to config runtime stack environment for T36713_idic_ControlNodePower 
```

**Comment by xiar** [comment]
@PaynePei Could you help to check why the smoke test failed? Looked like that all nodes didn't get the IP address from DHCP server.

**Comment by PaynePei** [comment]
all of the nodes didn't start

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* OPENIPMI_pull_request_trigger ******* 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_s2600kp_pr.ova_1467946914.12, BMC IP is: 192.168.133.92 
```

**Comment by fub2** [comment]
+1

**Pull request merged**
